export default {
  enter: 'Please Enter ',
  select: 'Please Select ',
  reset: 'Reset',
  search: 'Search',
  submit: 'Submit',
  selectDate: 'Select Date',
  selectTime: 'Select Time',
  startTime: 'Start Time',
  endTime: 'End Time',
  create: 'Create',
  edit: 'Edit',
  delete: 'Delete',
  newCreationSucceededL: 'New Creation Succeeded',
  editingSuccessfully: 'Editing Successfully',
  serialNumber: 'Serial Number',
  operate: 'Operate',
  tableIndexWidth: '150px',
  cancel: 'Cancel',
  confirm: 'Confirm'
}