export default {
  enter: '请输入',
  select: '请选择',
  reset: '重置',
  search: '查询',
  submit: '提交',
  selectDate: '选择日期',
  selectTime: '选择时间',
  startTime: '开始时间',
  endTime: '结束时间',
  create: '新建',
  edit: '编辑',
  delete: '删除',
  newCreationSucceededL: '新建成功',
  editingSuccessfully: '编辑成功',
  serialNumber: '序号',
  operate: '操作',
  tableIndexWidth: '70px',
  cancel: '取消',
  confirm: '确定'
}